import React, { useEffect, useState } from "react";
import {doc, addDoc, setDoc, collection, deleteDoc} from "firebase/firestore";
import { Trash2, Ticket, CalendarDays, Car  } from "lucide-react";

const PassManagementView = ({  db, appId, user, passes, uniqueBrands, uniqueGyms, parkingInfo }) => {
    const [selectedBrand, setSelectedBrand] = useState(uniqueBrands[0] || '');
    const [customBrand, setCustomBrand] = useState('');

    const [type, setType] = useState('punch');
    const [total, setTotal] = useState(10);
    const [months, setMonths] = useState(1);

    const [startDate, setStartDate] = useState(new Date().toISOString().split('T')[0]);
    const [endDate, setEndDate] = useState('');

    const [savingPass, setSavingPass] = useState(false);

    const [selectedParkGym, setSelectedParkGym] = useState(uniqueGyms[0] || '');
    const [customParkGym, setCustomParkGym] = useState('');
    const [parkingMemo, setParkingMemo] = useState('');
    const [savingPark, setSavingPark] = useState(false);

    useEffect(() => {
        if (startDate) {
            const d = new Date(startDate);
            if (type === 'period') {
                d.setMonth(d.getMonth() + months);
            } else {
                d.setMonth(d.getMonth() + 6);
            }
            setEndDate(d.toISOString().split('T')[0]);
        }
    }, [startDate, months, type]);

    const resetForm = () => {
        setSelectedBrand(uniqueBrands[0]);
        setCustomBrand('');
        setType('punch');
        setTotal(10);
        setMonths(1);
        setStartDate(new Date().toISOString().split('T')[0]);
    };

    const handleAddPass = async (e) => {
        e.preventDefault();
        const finalBrandName = selectedBrand === 'manual' ? customBrand.trim() : selectedBrand;
        if (!user || !finalBrandName || !startDate || !endDate) return;
        setSavingPass(true);

        const autoGeneratedName = type === 'punch' ? `${total}회권` : `${months}개월권`;

        try {
            await addDoc(collection(db, 'artifacts', appId, 'users', user.uid, 'passes'), {
                gym: finalBrandName,
                name: autoGeneratedName,
                type,
                start: startDate,
                end: endDate,
                total: type === 'punch' ? Number(total) : null,
                remaining: type === 'punch' ? Number(total) : null,
                dDay: 0
            });
            resetForm();
        } catch (err) { console.error(err); }
        finally { setSavingPass(false); }
    };

    const handleDeletePass = async (id) => {
        if (!window.confirm('이용권을 삭제하시겠습니까?')) return;
        await deleteDoc(doc(db, 'artifacts', appId, 'users', user.uid, 'passes', id));
    };

    const handleSaveParking = async (e) => {
        e.preventDefault();
        const finalParkGym = selectedParkGym === 'manual' ? customParkGym.trim() : selectedParkGym;
        if (!user || !finalParkGym || !parkingMemo) return;
        setSavingPark(true);
        try {
            const newParking = { ...parkingInfo, [finalParkGym]: parkingMemo };
            await setDoc(doc(db, 'artifacts', appId, 'users', user.uid, 'data', 'parking'), newParking, { merge: true });
            setCustomParkGym(''); setParkingMemo(''); setSelectedParkGym(uniqueGyms[0]);
        } catch (err) { console.error(err); }
        finally { setSavingPark(false); }
    };

    const handleDeleteParking = async (gymToDelete) => {
        if (!window.confirm('이 지점의 주차 정보를 삭제할까요?')) return;
        const newParking = { ...parkingInfo };
        delete newParking[gymToDelete];
        await setDoc(doc(db, 'artifacts', appId, 'users', user.uid, 'data', 'parking'), newParking);
    };

    return (
        <div className="space-y-4 animate-in fade-in">
            <section className="bg-white p-5 rounded-lg border border-border">
                {/*<div className="flex justify-between items-center mb-3">*/}
                {/*    <h3 className="text-xs text-text">*/}
                {/*        /!*<Ticket className="w-5 h-5 text-gray-800" />*!/*/}
                {/*        티켓 등록 관리*/}
                {/*    </h3>*/}
                {/*</div>*/}

                <form onSubmit={handleAddPass} className="space-y-4">
                    <div className="space-y-2">
                        <label className="text-xs text-text block">브랜드 선택 (공통 사용)</label>
                        <select value={selectedBrand} onChange={e => setSelectedBrand(e.target.value)} className="w-full min-w-0 h-[38px]  px-2.5 rounded-sm border border-border outline-none focus:ring-1 focus:ring-primary text-xs text-text">
                            {uniqueBrands.map(b => <option key={b} value={b}>{b}</option>)}
                            <option value="manual">직접 입력 (+)</option>
                        </select>
                        {selectedBrand === 'manual' && (
                            <input placeholder="새로운 브랜드명 (예: 알레)" className="w-full min-w-0 h-[38px]  px-2.5 rounded-sm border border-border outline-none focus:ring-1 focus:ring-primary text-xs text-text animate-in slide-in-from-top-2" value={customBrand} onChange={e => setCustomBrand(e.target.value)} required />
                        )}
                    </div>


                    <div className="space-y-2">
                        <div className="space-y-2">
                            <label className="text-xs text-text block">이용권 종류</label>
                            <select value={type} onChange={e => setType(e.target.value)} className="w-full min-w-0 h-[38px]  px-2.5 rounded-sm border border-border outline-none focus:ring-1 focus:ring-primary text-xs text-text">
                                <option value="punch">횟수권</option>
                                <option value="period">기간권</option>
                            </select>
                        </div>

                        {type === 'punch' ? (
                            <div className="space-y-2 bg-orange-50/50 p-2.5 rounded-sm border border-orange-100">
                                <div className="flex items-center justify-between h-[38px] bg-white p-2.5 rounded-sm border border-orange-100 min-w-0">
                                    <label className="text-xs text-text uppercase shrink-0 mr-4">전체 횟수 설정</label>
                                    <select value={total} onChange={e => setTotal(Number(e.target.value))} className="bg-transparent outline-none text-xs text-text min-w-0 text-right">
                                        <option value={5}>5회</option>
                                        <option value={10}>10회</option>
                                        <option value={15}>15회</option>
                                        <option value={20}>20회</option>
                                        <option value={30}>30회</option>
                                    </select>
                                </div>
                                <div className="flex items-center justify-between bg-white p-2.5 rounded-sm border border-gray-200 min-w-0">
                                    <label className="text-xs text-text uppercase shrink-0 mr-4">구매일</label>
                                    <input type="date" className="appearance-none bg-transparent outline-none text-xs text-gray-700 text-right w-full flex-1 min-w-0" value={startDate} onChange={e => setStartDate(e.target.value)} required />
                                </div>
                                <div className="flex items-center justify-between bg-white p-2.5 rounded-sm border border-rose-200 min-w-0">
                                    <label className="text-xs text-secondary uppercase shrink-0 mr-4">유효기간 (만료일)</label>
                                    <input type="date" className="appearance-none bg-transparent outline-none text-xs text-secondary text-right w-full flex-1 min-w-0" value={endDate} onChange={e => setEndDate(e.target.value)} required />
                                </div>
                            </div>
                        ) : (
                            <div className="space-y-2 bg-blue-50/50 p-2.5 rounded-sm border border-blue-100">
                                <div className="flex items-center justify-between  h-[38px]  bg-white p-2.5 rounded-sm border border-blue-100 min-w-0">
                                    <label className="text-xs text-text uppercase shrink-0 mr-4">기간 설정</label>
                                    <select value={months} onChange={e => setMonths(Number(e.target.value))} className="bg-transparent outline-none text-xs min-w-0 text-right">
                                        <option value={1}>1개월</option>
                                        <option value={3}>3개월</option>
                                        <option value={6}>6개월</option>
                                        <option value={12}>12개월</option>
                                    </select>
                                </div>
                                <div className="flex items-center justify-between bg-white h-[38px] p-2.5 rounded-sm border border-gray-200 min-w-0">
                                    <label className="text-xs text-text uppercase shrink-0 mr-4">시작일</label>
                                    <input type="date" className="appearance-none bg-transparent outline-none text-xs text-gray-700 text-right w-full flex-1 min-w-0" value={startDate} onChange={e => setStartDate(e.target.value)} required />
                                </div>
                                <div className="flex items-center justify-between bg-white h-[38px] p-2.5 rounded-sm border border-rose-200 min-w-0">
                                    <label className="text-xs text-secondary uppercase shrink-0 mr-4">만료일 (자동계산)</label>
                                    <input type="date" className="appearance-none bg-transparent outline-none text-xs text-secondary text-right w-full flex-1 min-w-0" value={endDate} onChange={e => setEndDate(e.target.value)} required />
                                </div>
                            </div>
                        )}
                    </div>

                    <button disabled={savingPass} className={`w-full h-[38px] py-2.5 text-white rounded-sm uppercase transition-all disabled:opacity-50 bg-primary text-xs`}>
                        {savingPass ? '처리 중...' : 'REGISTER TICKET 💳'}
                    </button>
                </form>

                <div className="mt-5 space-y-4">
                    <h3 className="text-xs font-semibold text-primary-500 border-t border-border pt-6">All Registered Tickets</h3>
                    {passes.map(p => (
                        <div key={p.id} className={`p-4 rounded-sm border flex justify-between items-center transition-all bg-gray-50 border-gray-100 min-w-0`}>
                            <div className="flex-1 min-w-0 pr-2">
                                <div className="flex items-center gap-2 mb-1">
                                    <span className={`text-[9px] px-2 py-0.5 rounded-md font-bold uppercase ${p.type === 'period' ? 'bg-blue-100 text-blue-600' : 'bg-orange-100 text-orange-600'}`}>{p.type === 'period' ? '기간권' : '횟수권'}</span>
                                    <h4 className="text-xs font-bold text-gray-800 truncate">{p.gym}</h4>
                                </div>
                                <p className="text-[11px] text-gray-800 font-bold mt-1.5 flex items-center gap-1">
                                    {p.name} {p.type === 'punch' && <span className="text-orange-500 ml-1">({p.remaining}회 남음)</span>}
                                </p>
                                {p.start && p.end && (
                                    <p className="text-xs text-gray-500 mt-1 flex items-center gap-1 truncate">
                                        <CalendarDays className="w-3 h-3 shrink-0" /> {p.start} ~ <span className="">{p.end}</span>
                                    </p>
                                )}
                            </div>
                            <div className="flex flex-col gap-2 shrink-0">
                                <button onClick={() => handleDeletePass(p.id)} className="text-gray-400 hover:text-rose-500 bg-white p-2 rounded-sm border border-border transition-colors"><Trash2 className="w-4 h-4" /></button>
                            </div>
                        </div>
                    ))}
                    {passes.length === 0 && <p className="text-center text-xs text-gray-400 py-6 border border-dashed border-gray-200 rounded-xl bg-gray-50/50">등록된 이용권이 없습니다.</p>}
                </div>
            </section>

            <section className="bg-white p-6 rounded-lg border border-border">
                <h3 className="text-xs font-bold text-gray-800 uppercase mb-5">
                    {/*<Car className="w-5 h-5 text-blue-600" /> */}
                    지점별 주차장
                </h3>
                <form onSubmit={handleSaveParking} className="space-y-2">
                        <label className="text-xs text-text block">방문하는 지점 선택</label>
                        <select value={selectedParkGym} onChange={e => setSelectedParkGym(e.target.value)} className="w-full min-w-0 h-[38px] px-2.5 rounded-sm border border-border outline-none focus:ring-1 focus:ring-primary text-xs text-text">
                            {uniqueGyms.map(g => <option key={g} value={g}>{g}</option>)}
                            <option value="manual">직접 입력 (+)</option>
                        </select>
                        {selectedParkGym === 'manual' && (
                            <input placeholder="새로운 지점명 입력 (예: 더클라임 신림)" className="w-full min-w-0 h-[38px]  px-2.5 rounded-sm border border-border outline-none focus:ring-1 focus:ring-primary text-xs text-text animate-in slide-in-from-top-2" value={customParkGym} onChange={e => setCustomParkGym(e.target.value)} required />
                        )}

                    <input placeholder="해당 지점의 주차 조건 (예: 건물 지하 불가)" className="w-full min-w-0 h-[38px]  px-2.5 rounded-sm border border-border outline-none focus:ring-1 focus:ring-primary text-xs text-text" value={parkingMemo} onChange={e => setParkingMemo(e.target.value)} required />

                    <button disabled={savingPark} className="w-full h-[38px] py-2.5 text-white rounded-sm uppercase transition-all disabled:opacity-50 bg-primary text-xs">
                        {savingPark ? '저장 중...' : 'SAVE PARKING INFO 🚗'}
                    </button>
                </form>

                <div className="mt-5 space-y-3">
                    <h3 className="text-xs font-semibold text-primary-500 border-t border-border pt-6">Saved Parking Infos</h3>
                    {Object.entries(parkingInfo).map(([gymName, info]) => (
                        <div key={gymName} className="bg-gray-50 p-4 rounded-sm border border-border flex justify-between items-center min-w-0">
                            <div className="min-w-0 pr-2">
                                <h4 className="text-xs font-bold text-gray-800 truncate">{gymName}</h4>
                                <p className="text-xs text-blue-600  mt-0.5 truncate">{info}</p>
                            </div>
                            <button onClick={() => handleDeleteParking(gymName)} className="text-gray-400 hover:text-rose-500 hover:bg-white p-2 rounded-xl transition-colors shrink-0"><Trash2 className="w-4 h-4" /></button>
                        </div>
                    ))}
                    {Object.keys(parkingInfo).length === 0 && <p className="text-center text-xs text-gray-400 py-6 border border-dashed border-gray-200 rounded-xl bg-gray-50/50">저장된 주차 정보가 없습니다.</p>}
                </div>
            </section>

        </div>
    );
};

export default PassManagementView;